### ISSUE TITLE
Issue loading project

### ISSUE THREAD

**Issue by SeanRhone** [scottbrady91/IdentityServer4-Example#1]
Trying to work through your blog post which includes this project and when I try to load this project using VS 2015 Enterprise I get "We were unable to automatically populate your Visual Studio Team Services Account."

How do I get around this?

**Comment by scottbrady91** [comment]
I dunno. This project doesn't use VSTS in any way, so this sounds like there's an issue with Visual Studio. Also, this project uses .NET Core & csproj which is only support by VS2017.

**Comment by scottbrady91** [comment]
Any news?

**Comment by SeanRhone** [comment]
Guessing the issue is I'm using VS2015 and not 2017? Past that, still
unable to open the projects.

**Comment by scottbrady91** [comment]
I imagine so. Strange that it is VSTS that is throwing the error though. So yes, you need to use VS2017 to open this project. Community edition will do.
