### ISSUE TITLE
No authentication handler is configured to authenticate for the scheme: idsrv

### ISSUE THREAD

**Issue by StevenTCramer** [scottbrady91/IdentityServer4-Example#2]
I clone the repo and build in VS2017 run and when I click on 

`Click here to manage your stored grants.`

I get the following:

InvalidOperationException: No authentication handler is configured to authenticate for the scheme: idsrv

**Comment by scottbrady91** [comment]
Hmmm, strange... The authentication scheme `idsrv` should not be used anymore, by using `AddAspNetIdentity<T>` we are overwriting this to be `Identity.Application`, which is the scheme used by ASP.NET Core Identity.

Let me look into it.

**Comment by scottbrady91** [comment]
Oh, this'll do it:
```
[SecurityHeaders]
    [Authorize(ActiveAuthenticationSchemes = IdentityServerConstants.DefaultCookieAuthenticationScheme)]
    public class GrantsController : Controller
```

You need to change the `ActiveAuthenticationSchemes` to `Identity.Application`.

As I say in the article, this is just a quick start UI and not designed to be used with ASP.NET Core Identity (or production). Hence the hard-coded auth type.

I'll update the article & repo next time I'm in there.

**Comment by StevenTCramer** [comment]
Excellent thanks.  Will take a look today.
