### ISSUE TITLE
Identity Server logout not working in example

### ISSUE THREAD

**Issue by blankenbush** [scottbrady91/IdentityServer4-Example#3]
Hi Scott,

I am trying to get your example working and can't understand why logout it not working.

Steps
1. download zip, open in VS 2017 (note: did not make any code changes)
2. run project **ScottBrady91.IdentityServer4.Example** ONLY
3. login as scott / Password123!
4. go to menu under scott and select logout.  on screen that comes up select "yes".
5. click "IdentityServer4" in header.
6. user scott is still logged in.

It seems the authentication cookie is not deleted or expired.  Thought I was on to something when I read this in your article. 

https://www.scottbrady91.com/Identity-Server/Getting-Started-with-IdentityServer-4#ASPNET-Core-Identity

**Because ASP.NET Identity also changes the default authentication scheme, any instances of IdentityServerConstants.DefaultCookieAuthenticationScheme and IdentityServerConstants.ExternalCookieAuthenticationScheme, should be changed to IdentityConstants.Application and IdentityConstants.ExternalScheme respectively.**

Thanks,
David

**Comment by AlexandraDamaschin** [comment]
Did you resolved this issue? Its the same in my case. I follow his [tutorial](https://www.scottbrady91.com/Identity-Server/Getting-Started-with-IdentityServer-4) but logout still doesn\`t work.

**Comment by scottbrady91** [comment]
Do you have logs for the logout request?

**Comment by Arpanx** [comment]
[HttpPost]
[ValidateAntiForgeryToken]
public async Task<IActionResult> Logout(LogoutInputModel model)

model always null

**Comment by scottbrady91** [comment]
If logoutId is null, that should be fine. In other words, you've arrived at this action manually and not as part of an OpenID Connect end session request.

It sounds like the QuickStart UI on this one is just a little out of date. I'll update it when I get a chance.
