### ISSUE TITLE
Update data from configuration file in database

### ISSUE THREAD

**Issue by AlexandraDamaschin** [scottbrady91/IdentityServer4-Example#4]
https://github.com/scottbrady91/IdentityServer4-Example/blob/60144a22bb2abc1c51129741780726cc91af9ebd/src/ScottBrady91.IdentityServer4.Example/Startup.cs#L60

Question: you are using this method to initialize the database and seed data from the configuration file. 

After initialize and configuration, how can you still add other users or update information? 
I modified something in the config file and update the database but nothing changes in my database.

**Comment by scottbrady91** [comment]
That method is purely for bootstrapping the database with some test data. If you need to update it, you'll either have to do this in the database manually or delete and recreate the tables.

**Comment by AlexandraDamaschin** [comment]
So there is no way for me to update the database with a command like 
`dotnet ef database update -c ApplicationDbContext` ?

**Comment by scottbrady91** [comment]
Not that I'm aware of. Maybe the seed data style stuff from EF 6 has made it's way to EF Core?

Either way, this bootstrap method shouldn't really be used in production or as a method of maintaining data. Check out tools such as AdminUI for that

**Comment by AlexandraDamaschin** [comment]
Good to know! Thanks for clarifying this.
